"""
Group chat with agents
======================

This example demonstrates how to use AutoGen to create a group chat with multiple agents.
The group chat will alternate between the agents until a termination condition is met.
"""

import asyncio
import os
import sys
from autogen_agentchat.agents import AssistantAgent
from autogen_agentchat.teams import RoundRobinGroupChat
from autogen_agentchat.conditions import TextMentionTermination
from autogen_agentchat.ui import Console
from autogen_ext.models.openai import OpenAIChatCompletionClient


# Add src directory to Python path for imports
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from enums.ai_models import OpenAIModels  # type: ignore
from utils.get_env import get_env_variables  # type: ignore

os.system("clear")
envs = get_env_variables()

""" 
    Group Chat
    - This is used to create a group chat with multiple agents.
    - The group chat will alternate between the agents until a termination condition is met.
    - The termination condition is a text termination, which will cause the chat to terminate when the text "APPROVE" is received.
"""
async def main() -> None:
    model_client = OpenAIChatCompletionClient(
        base_url="https://router.requesty.ai/v1",
        api_key=envs["REQUESTY_API_KEY"],
        model=OpenAIModels.gpt5_nano,
        model_info={
            "vision": False,
            "family": "gpt-5",
            "function_calling": True,
            "json_output": True,
            "multiple_system_messages": True,
            "structured_output": True,
        },
        temperature=1,
        # seed=42,
        # temperature=0.0,
    )

    writer = AssistantAgent(
        name="writer",
        description="A writer.",
        system_message="You are a writer.",
        model_client=model_client,
    )

    critic = AssistantAgent(
        name="critic",
        description="A critic.",
        system_message="You are a critic, you review the work of the writer and provide constructive feedback to help improve the quality of the content. You must give review of the work that is generated by writer. Reply only 'APPROVE' if the task is done.",
        model_client=model_client,
    )

    # The termination condition is a text termination, which will cause the chat to terminate when the text "APPROVE" is received.
    termination = TextMentionTermination("APPROVE")

    # The group chat will alternate between the writer and the critic.
    group_chat = RoundRobinGroupChat(
        [writer, critic], termination_condition=termination, max_turns=12
    )

    # `run_stream` returns an async generator to stream the intermediate messages.
    stream = group_chat.run_stream(
        task="Write a short short blog in 150 words about how to train a dog."
    )
    # `Console` is a simple UI to display the stream.
    await Console(stream)
    # Close the connection to the model client.
    await model_client.close()


if __name__ == "__main__":
    asyncio.run(main())
